# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    # 这是 github 官方的一个 action，用于 clone 该仓库的源码到工作流中，
    - uses: actions/checkout@v2
    - name: Build use Node.js ${{ matrix.node-version }}
      run: npm install && npm run build
    - name: deploy
      uses: cross-the-world/scp-pipeline@master
      env:
        WELCOME: "ssh scp ssh pipelines"
        LASTSSH: "Doing something after copying"
      with:
        host: ${{ secrets.TC_HOST }}
        user: ${{ secrets.TC_USER }}
        pass: ${{ secrets.TC_PASS }}
        connect_timeout: 10s
        local: './build/*'
        remote: /www/wwwroot/oak/build
